### ISSUE TITLE
wp.org review

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/algibro-shop#8]
- [x] Depracated tags should be removed from style.css
- [x] All 3rd party item's needs licence declaration: bootstrap, images, fonts
- [x] Unused files and codes should be removed:  *.map files
- [x] All content queried by get_theme_mod needs escaping
- [x] Child theme's text-domain should be used
- <?php esc_html_e('Toggle navigation','azera-shop'); ?></span>
- esc_html__('Header button label:','azera-shop')
- esc_html__('From the creators of the popular Zerif Lite meet the new ecommerce theme','azera-shop')
- etc.
- [x] Using import is not allowed in style.css
- [x] Header visibility option has not worked ( this may happen from the parent theme, you need to check that too)
- [x] Text color option has changed h\* tags color( this may happen from the parent theme, you need to check that too)
- [x] Title color option has not worked( this may happen from the parent theme, you need to check that too)
- [x] If i choose to use a background image, all text become unreadable. It could be good to implement a wrapper with a solid color background.
- [x] Front page settings option has not worked even if i set a page with frontpage template
- [x] A watermarked place holder image should not be displayed if a post does not have a featured image. If you want to use default one you should make proper changes to make it easily changeable by the user. (in the parent theme, we'll leave it like it is, you may need to change in the parent theme, to get the image from child, if it's there, and add a simple image in child, without a watermark)
- [x] Fixed header positioning is used as a result if i choose to use a widget (e.g. search) in header sidebar, header overflows into content area.
- [x] RTL feature needs more work or just remove rtl-support tag. ( If it takes more then 20min I think it's better to remove it)

@cristian-ungureanu please try to fix this in the next couple of days, so we can submit the update.
Also, please have separate commits for each issue.
And, make sure the parent theme will not be changed (unless bugs are fixed for child theme) and the strings are the same in parent.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu you didn't need to create separate issues for this :) when we have smaller tasks, maybe it's better this way, to have one issue with tasks list. And you just need to reference this issue in the commit, plus have a clear message for the commit.
Also, I don't see the pull requst :)

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , most of the issues created are not in this review. All my commits reference this issue or an issue that I found when testing the child theme. There is no pull request yet because there are still some issues here.
